<?php

static $keyMap_GetGJLevels21 = [ // GetGJLevels21.php
    1  => 'level_id',
    2  => 'level_name',
    5  => 'level_version',
    6  => 'creator_id',
    8  => 'difficultyDenominator',
    9  => 'level_difficulty',
    10 => 'downloads',
    12 => 'audio_track',
    13 => 'game_version',
    14 => 'likes',
    17 => 'is_demon',
    43 => 'demon_difficulty',
    25 => 'is_auto',
    18 => 'stars',
    19 => 'featured_score',
    42 => 'is_epic',
    45 => 'object_count',
    3  => 'description_base64',
    15 => 'two_player_mode',
    30 => 'song_id',
    31 => 'is_ldm',
    37 => 'coins_verified',
    38 => 'password',
    39 => 'level_length',
    46 => 'is_cp_verified',
    47 => 'is_copied',
    35 => 'record_id'
];